version: '3'

networks:
  codebank: 
    external:
      name: codebank

services:
  app:
    container_name: codebank
    build: .
    ports:
      - "50051:50051"
    volumes:
      - .:/go/src
    networks:
      - codebank
  db:
    image: postgres:9.6
    restart: always
    tty: true
    volumes: 
      - .pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: codebank
    ports:
      - "5432:5432"
    networks:
      - codebank
  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@user.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "9000:80"
    depends_on:
      - db
    networks:
      - codebank
  
        

